### ISSUE TITLE
Add some packages to Gnome flavour

### ISSUE THREAD

**Issue by prescott66** [manjaro/iso-profiles#98]
I can recommend to add these packages to Gnome as default apps:

gnome-contacts
vinagre
rygel
gnome-documents
gnome-photos

**Comment by Ste74** [comment]
- Since I do not use my pc to catalog my photos because gnome-photos instead of gthumbs ?
- gnome-contact make a sense..
- gnome-document again why? We ship more professional suite like Libreoffice
- vinagre and rygel is only a plus and not all people use  media server and a remote desktop functionality ..

**Comment by Ste74** [comment]
- Since I do not use my pc to catalog my photos because gnome-photos instead of gthumbs ?
- gnome-contact make a sense..
- gnome-document again why? We ship more professional suite like Libreoffice
- vinagre and rygel is only a plus and not all people use  media server and a remote desktop functionality ..

**Comment by Ste74** [comment]
- Since I do not use my pc to catalog my photos because gnome-photos instead of gthumbs ?
- gnome-contact make a sense..
- gnome-document again why? We ship more professional suite like Libreoffice
- vinagre and rygel is only a plus and not all people use  media server and a remote desktop functionality ..

**Comment by prescott66** [comment]
OK. I just want to make gnome more gnome for everybody, out of the box.
So you will add gnome-contact app only.

**Comment by Ste74** [comment]
I'm always open to listen :) ... if i add your packages i have two program for the same job..

**Comment by prescott66** [comment]
@Ste74 i have found two programs for the same job: gucharmap and gnome-characters....i think it will better to keep only gnome-characters

**Comment by Ste74** [comment]
Thank you 
1124ae9e2524c5bbea5977e77f0ae62ad3645d83
